trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  projectName: 'QsMessaging'
  solutionName: 'QsMessaging'
  nugetSource: 'https://api.nuget.org/v3/index.json'  # NuGet.org Feed
  nugetApiKey: $(NuGetApiKey)  # Ensure this secret is defined in Azure DevOps

jobs:
  - job: BuildAndPublish
    displayName: 'Build, Test, and Publish'
    pool:
      name: 'Default'

    steps:
      # Step 1: Use .NET Core SDK
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      # Step 2: Install NuGet Tool
      - task: NuGetToolInstaller@1

      # Step 3: Restore Dependencies
      - script: dotnet restore $(projectName).sln
        displayName: 'Restore NuGet Packages'

      # Step 4: Build the Project
      - script: dotnet build $(projectName).sln --configuration $(buildConfiguration) --no-restore
        displayName: 'Build Project'

      # Step 5: Run Unit Tests (Optional)
      #- script: dotnet test $(projectName).sln --configuration $(buildConfiguration) --no-build --logger trx
      #  displayName: 'Run Unit Tests'

      # Step 6: Pack the NuGet Package
      - script: dotnet pack $(solutionName)/$(projectName).csproj --configuration $(buildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory)
        displayName: 'Create NuGet Package'

      # Step 7: Push pack
      - script: dotnet nuget push $(Build.ArtifactStagingDirectory)\*.nupkg --api-key $(nugetApiKey) --source https://api.nuget.org/v3/index.json
        displayName: 'Push NuGet Package'

      # Step 7: Authenticate with NuGet.org
      - task: NuGetAuthenticate@1
        inputs:
          nuGetServiceConnections: 'NuGetOrgConnection'  # Create this connection in Azure DevOps

      # Step 8: Publish the NuGet Package to NuGet.org
      - task: NuGetCommand@2
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          publishVstsFeed: false
          nuGetFeedType: 'external'
          #publishPackageUrl: $(nugetSource)
          externalFeedUrl: $(nugetSource)
          apiKey: $(nugetApiKey)  # This API Key is for NuGet.org
        displayName: 'Publish NuGet Package to NuGet.org'

